### PR TITLE
Add spdx names to licenses

### PR DESCRIPTION
**Pull request by pablrod**
[SPDX](https://spdx.org/) project defines a set of identifiers for [licenses](https://spdx.org/licenses). This pull request just add a method to get that identifier.

In CPAN there is [License::Syntax](https://metacpan.org/pod/release/JNW/License-Syntax-0.13/Syntax.pm) but doesn't offer an API to get the spdx name, nor the mapping between Software::License name. Although there is a [file](https://metacpan.org/source/JNW/License-Syntax-0.13/synopsis.csv) with a list of licenses and the spdx name and identifier.

### CODE REVIEW

**Comment by karenetheridge** [comment]
Looks good to me. 👍

**Comment by Leont** [comment]
Sounds sensible enough to me. Probably we should use it if we ever create a Meta 3.0.

**Comment by dolmen** [comment]
Here is some input data that could be used for a more extensive testsuite: https://github.com/OpenSourceOrg/licenses/blob/master/licenses/spdx/spdx.json (related to #52)

**Comment by pablrod** [comment]
Good! I'll use that input data to improve the testsuite.

**Comment by pablrod** [comment]
I've extended the tests to cover all `Software::License` modules that have spdx name (https://github.com/Perl-Toolchain-Gang/Software-License/pull/54/commits/c45950a08889593dc20cd990309e917f15ea265e).

I think it would be useful a method to get the license via spdx name, I mean:

```perl
my $license_object = Software::LicenseUtils->new_from_spdx_name( {
  spdx_name => 'MPL-2.0',
  holder => 'X. Ample'
}) ;
```
So I've added this method https://github.com/Perl-Toolchain-Gang/Software-License/pull/54/commits/dc677bc983bf87abb9a5e681c3f9d5d0c29c2d64

@dolmen is ok the testsuite?

**Comment by Leont** [comment]
I think it's more sensible to think in terms of spdx expressions than in names, especially because the most commonly used license is such an expression.

**Comment by pablrod** [comment]
Thanks for your comment!

You're right, the term "name" is not a good option. I've looked up in [The Software Package Data Exchange](https://spdx.org/) web, and they use the terms:
* 'short identifier' (Individual license pages in SPDX website, for example [MPL](https://spdx.org/licenses/MPL-2.0.html) and [wikipedia](https://en.wikipedia.org/wiki/Software_Package_Data_Exchange#License_syntax)
* 'identifier' [SPDX web list](https://spdx.org/licenses/)

The GitHub repo [spdx/license-list-data](https://github.com/spdx/license-list-data) uses in JSON files the key 'licenseId' [licenses.json](https://github.com/spdx/license-list-data/blob/master/json/licenses.json)

The term 'identifier' is consistent with the [OpenSourceOrg/api](https://github.com/OpenSourceOrg/api/blob/master/doc/endpoints.md#identifier). (Consistent with the [Perl client](https://metacpan.org/pod/OpenSourceOrg::API))

So I'm going to change the term "spdx_name" to "spdx_identifier".

Please let me know if there is something wrong with "spdx_identifier".

**Comment by Leont** [comment]
> Please let me know if there is something wrong with "spdx_identifier".

I think that is useful for `new_from_spdx_name`, but it's not really useful for meta files. Those would need a `spdx_expression` that is implemented by all License types. E.g. the Perl license would return something like `Artistic-1.0-Perl OR GPL-1.0+`

**Comment by pablrod** [comment]
Oh good point! Then I'll change the `spdx_name` in individual license files to `spdx_expression` and implement it for all licenses. 

Ok?

**Comment by Leont** [comment]
> Ok?

That sounds good.

**Comment by pablrod** [comment]
Now `spdx_expression` is implemented for all licenses. Also I've added a default in `Software::License::spdx_expression` that use the module name, for those modules out of this distribution (for example: [Software::License::CCpack](https://metacpan.org/pod/Software::License::CCpack))

**Comment by Leont** [comment]
> Also I've added a default in Software::License::spdx_expression that use the module name, for those modules out of this distribution (for example: Software::License::CCpack)

I think it's more helpful to not return anything than guess something that's almost but not quite correct. Eg for `Software::License::CC_BY_4_0` the correct result would be `CC-BY-4.0`, not `CC_BY_4_0`. It's not that hard for `CCPack` and friends to add support for this.

**Comment by Leont** [comment]
> Also I've added a default in Software::License::spdx_expression that use the module name, for those modules out of this distribution (for example: Software::License::CCpack)

I think it's more helpful to return undef than guess something that's probably not correct. Eg for `Software::License::CC_BY_4_0` the correct result would be `CC-BY-4.0`, not `CC_BY_4_0`. It's not that hard for `Software::License` extensions to add support for this anyone.

**Comment by pablrod** [comment]
Yes, I totally agree. I've changed that. Now the method `spdx_expression` in `Software::License` returns `undef`.

**Comment by Leont** [comment]
This is now part of Software-License 0.103014 :-)

**Pull request closed without merging**
