### PR TITLE
Add the EUPL license to Software::License

### PR DESCRIPTION
**Pull request by waterkip**

### CODE REVIEW

**Comment by haarg** [comment]
The meta_name and meta2_name methods should return valid license strings for CPAN [meta v1](https://metacpan.org/pod/distribution/CPAN-Meta/lib/CPAN/Meta/History/Meta_1_4.pod#license) and [meta v2](https://metacpan.org/pod/CPAN::Meta::Spec#license).

The full license text should be included, not just a reference to a URL.

**Comment by Leont** [comment]
> The meta_name and meta2_name methods should return valid license strings for CPAN meta v1 and meta v2.

In both cases that should be `open_source`.

[SPDX](https://github.com/Perl-Toolchain-Gang/Software-License/pull/54) support would be helpful here.

> The full license text should be included, not just a reference to a URL.

Agreed.

**Comment by karenetheridge** [comment]
> The meta_name and meta2_name methods should return valid license strings for CPAN meta v1 and meta v2.

As a breadcrumb to contributors, it would be useful to add a test that checked that all licence classes returned correct strings here.

**Comment by waterkip** [comment]
I've updated the PR with your comments. I've kept the short version of the license in the __NOTICE__. 

Cheers,
Wesley

**Comment by waterkip** [comment]
Is there any indication when this PR can/will be merged?

**Comment by Leont** [comment]
> Is there any indication when this PR can/will be merged?

I expect we'll look over it at the tPerl Toolchain Summit next month. A new release of Software::License is due.

**Comment by Leont** [comment]
Given that this license is versioned, the class should probably also be (also, this is 1.1 but 1.2 has been released since this ticket was opened. Is it desirable to add both?)

**Comment by Leont** [comment]
I've squashed this, fixed it up to make dzil happy (PkgVersion wants a newline after the package statement) and merged it.

Enjoy Software::License 0.103013 :-)

**Pull request closed without merging**
