### PR TITLE
update the text of the Artistic License 1.0, it was changed upstream.

### PR DESCRIPTION
**Pull request by xenu**
See: https://perl5.git.perl.org/perl.git/commit/d6f040aa42ca83e5e2ddbd3502921c8fee6197c4

### CODE REVIEW

**Comment by xenu** [comment]
BTW, this gives us opportunity to trim trailing whitespace, as mentioned here: https://github.com/Perl-Toolchain-Gang/Software-License/pull/30#issuecomment-218325545

**Comment by Leont** [comment]
IANAL, but I think we can do this.

**Comment by xenu** [comment]
Done.

**Comment by rjbs** [comment]
Thanks, applied!

**Pull request merged**
