### PR TITLE
Adapted to use Software::License::Template for templates

### PR DESCRIPTION
**Pull request by polettix**
With reference to this ticket:

https://rt.cpan.org/Ticket/Display.html?id=75395

I set up a Software::License::Template (still to be uploaded on CPAN but here on github: https://github.com/polettix/software-license-template) to contain all the data and modified S::L to take them from there.

All tests are fine and I added a couple more for trickier licenses. It might possibly be the case to add some more.

Let me know what you think about this arrangement, I'll release S::L::Template as soon as I know that you're willing to take this route.

### CODE REVIEW

**Comment by karenetheridge** [comment]
Having a little more common code to facilitate creating new licence classes is a good idea, but I'm not sure if the approach here is the right one. I will take a closer look later.

**Comment by rjbs** [comment]
I think I agree with @karenetheridge.  It might be much simpler to just strip out the prereqs that S-L is using to make this more palatable to toolchain use.

**Comment by rjbs** [comment]
I vote no.  I think we should keep the templates in this distribution, but probably move them to their own files in a sharedir.

**Comment by Leont** [comment]
> I vote no. I think we should keep the templates in this distribution, but probably move them to their own files in a sharedir.

That would probably be more sensible, though I believe some extensions are depending on the current way.

**Comment by polettix** [comment]
Looking at it after 12 years, the initial intent of a separate module was to follow Schwern's request to separate data from the module, to allow bundling the data without the need to draw lots of prerequisites for S::L.

Anyway, a no is no.

**Pull request closed without merging**
